flowchart:
  nodes:
    - id: "jenerator1"
      label: "Jenerator 1"
      description: "Çıkış Voltaj: ${cikis_voltaj{instance='jenerator1tepesu'}} V"
      x: 100
      y: 200
      style:
        fill: ${cikis_voltaj{instance='jenerator1tepesu'}} > 220 ? 'green' : 'red'
  edges: []
