{
  "nodes": [
    { "id": "server1", "label": "Server 1", "x": 100, "y": 100 },
    { "id": "server2", "label": "Server 2", "x": 300, "y": 100 }
  ],
  "edges": [
    { "from": "server1", "to": "server2", "label": "Connection" }
  ]
}
