panels:
  - name: "Jenerator 1 Çıkış Voltajı"
    selector: '[id="jenerator1"]'
    query: 'cikis_voltaj{instance="jenerator1tepesu"}'
    type: "gauge"
    thresholds:
      - value: 200
        color: "red"
      - value: 220
        color: "yellow"
      - value: 240
        color: "green"
    unit: "V"
  
  - name: "Jenerator 2 Çıkış Voltajı"
    selector: '[id="jenerator2"]'
    query: 'cikis_voltaj{instance="jenerator2tepesu"}'
    type: "gauge"
    thresholds:
      - value: 200
        color: "red"
      - value: 220
        color: "yellow"
      - value: 240
        color: "green"
    unit: "V"

  - name: "Eaton UPS 1 Çıkış Voltajı"
    selector: '[id="eatonups1-cikis"]'
    query: 'cikis_voltaj{instance="eatonupstepesu"}'
    type: "gauge"
    thresholds:
      - value: 200
        color: "red"
      - value: 220
        color: "yellow"
      - value: 240
        color: "green"
    unit: "V"

  - name: "Eaton UPS 1 Giriş Voltajı"
    selector: '[id="eatonups1-giris"]'
    query: 'giris_voltaj{instance="eatonupstepesu"}'
    type: "gauge"
    thresholds:
      - value: 200
        color: "red"
      - value: 220
        color: "yellow"
      - value: 240
        color: "green"
    unit: "V"

  - name: "Eaton UPS 2 Çıkış Voltajı"
    selector: '[id="eatonups2-cikis"]'
    query: 'cikis_voltaj{instance="eatonups2tepesu"}'
    type: "gauge"
    thresholds:
      - value: 200
        color: "red"
      - value: 220
        color: "yellow"
      - value: 240
        color: "green"
    unit: "V"

  - name: "Eaton UPS 2 Giriş Voltajı"
    selector: '[id="eatonups2-giris"]'
    query: 'giris_voltaj{instance="eatonups2tepesu"}'
    type: "gauge"
    thresholds:
      - value: 200
        color: "red"
      - value: 220
        color: "yellow"
      - value: 240
        color: "green"
    unit: "V"
