flowchart:
  nodes:
    - id: "jenerator1"
      label: "Jenerator 1"
      description: "Çıkış Voltaj: cikis_voltaj{instance='jenerator1tepesu'} V"
      x: 150
      y: 200
      style:
        fill: cikis_voltaj{instance='jenerator1tepesu'} > 220 ? 'green' : 'red'
    - id: "ups1"
      label: "UPS 1"
      description: "Durum: ${durum{instance='ups1'}}"
      x: 400
      y: 200
      style:
        fill: ${durum{instance='ups1'}} == '1' ? 'green' : 'red'
  edges:
    - from: "jenerator1"
      to: "ups1"
      label: "Bağlantı"
      style:
        color: "blue"
