flowchart:
  nodes:
    - id: "jenerator1tepesu"
      label: "Jeneratör 1"
      description: "Çıkış Voltajı: ${cikis_voltaj{instance='jenerator1tepesu'}} V"
      color: "${cikis_voltaj{instance='jenerator1tepesu'} > 200 ? 'green' : 'red'}"

    - id: "jenerator2tepesu"
      label: "Jeneratör 2"
      description: "Çıkış Voltajı: ${cikis_voltaj{instance='jenerator2tepesu'}} V"
      color: "${cikis_voltaj{instance='jenerator2tepesu'} > 200 ? 'green' : 'red'}"

    - id: "eatonupstepesu"
      label: "Eaton UPS 1"
      description: |
        Çıkış Voltajı: ${cikis_voltaj{instance='eatonupstepesu'}} V
        Giriş Voltajı: ${giris_voltaj{instance='eatonupstepesu'}} V
      color: "${cikis_voltaj{instance='eatonupstepesu'} > 200 && giris_voltaj{instance='eatonupstepesu'} > 200 ? 'green' : 'red'}"

    - id: "eatonups2tepesu"
      label: "Eaton UPS 2"
      description: |
        Çıkış Voltajı: ${cikis_voltaj{instance='eatonups2tepesu'}} V
        Giriş Voltajı: ${giris_voltaj{instance='eatonups2tepesu'}} V
      color: "${cikis_voltaj{instance='eatonups2tepesu'} > 200 && giris_voltaj{instance='eatonups2tepesu'} > 200 ? 'green' : 'red'}"
