gradientMode: "hue"
cellIdPreamble: "cell-"
cells: 
  jenerator1:
    dataRef: "cikis_voltaj{instance=\"jenerator1tepesu\"}"
    label:
      separator: "cr"
      units: "V"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "gen"
  jenerator2:
    dataRef: "cikis_voltaj{instance=\"jenerator2tepesu\"}"
    label:
      separator: "cr"
      units: "V"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "gen"
  eatonupstepesu_out:
    dataRef: "cikis_voltaj{instance=\"eatonupstepesu\"}"
    label:
      separator: "cr"
      units: "V"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "gen"
  eatonupstepesu_in:
    dataRef: "giris_voltaj{instance=\"eatonupstepesu\"}"
    label:
      separator: "cr"
      units: "V"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "gen"
  eatonups2tepesu_out:
    dataRef: "cikis_voltaj{instance=\"eatonups2tepesu\"}"
    label:
      separator: "cr"
      units: "V"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "gen"
  eatonups2tepesu_in:
    dataRef: "giris_voltaj{instance=\"eatonups2tepesu\"}"
    label:
      separator: "cr"
      units: "V"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "gen"
