---

colors:
  red: "#FF0000"
  amber: "#FFBF00"
  green: "#00FF00"

# The grafana variable has to impact a query, but if it does the first match
# per variable will be applied to the thresholds. If using with test-data you
# can get around this 'update' restriction by adding the variable to your panel title.
variableThresholdScalars:
  environment:
    - {variableValuePattern: "jenerator", thresholdScalar: 0.2, cellIdPatternScope: [".*jenerator.*", ".*eatonupstepesu.*"]}

thresholds:
  queuecount:
    - {color: "green", level: 10}
    - {color: "amber", level: 30}
    - {color: "red", level: 60}
  gen:
    - {color: "green", level: 200}
    - {color: "amber", level: 300}
    - {color: "red", level: 1500}
  dbtrans:
    - {color: "green", level: 200}
    - {color: "amber", level: 230}
    - {color: "red", level: 240}
  queuelatency:
    - {color: "green", level: 30}
    - {color: "amber", level: 60}
    - {color: "red", level: 90}
  normalized:
    - {color: "green", level: 0.4}
    - {color: "amber", level: 0.6}
    - {color: "red", level: 0.8}